import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex ", justifyContent: "center" }}>
          <nav style={{ marginRight: "10px" }}>
            <Link href="/posts">posts</Link>
          </nav>
          <nav>
            <Link href="/article">article</Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
